name: MythicPet
version: 1.3.13.4
main: net.brian.mythicpet.MythicPets
api-version: 1.13
author: Sleep_AllDay
depend:
  - MythicMobs
  - PlayerDataSync
softdepend:
  - WorldGuard
  - MMOItems
  - MythicLib
  - LibsDisguises
  - ModelEngine
  - PlaceholderAPI

commands:
  mythicpet:
    usage: /<command>
    aliases: [mp]